### PR TITLE
Fix non-working backend

### PR DESCRIPTION
**Pull request by DorianBDev**
## Problem

- The "arm" branch (that fixes the install on ARM architecture) had an issue with the backend (api) install (not working) due to a file type treated as a binary rather than a zip.

## Solution

- A simple unzip of the downloaded file in a temp dir, and a copy of the binary file to the same place as before.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

I tried to stick to your commit message style, hope it's OK. Also note that I only tested this with ARM (but it should work anyway, only the filename changes). This commit also adds a clearer separation between backend and frontend in the scripts.

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Gilbog** [comment]
Question from the YunoHost newbies: How can we install "this" Vikunja version on our YunoHost Raspberries? Please help out with the necessary termial command or whatever it takes -- for those who are still learning all this ... Thanks!

**Comment by ericgaspar** [comment]
If you want to test this branch:
`sudo yunohost app install https://github.com/DorianBDev/vikunja_ynh/tree/arm`

**Comment by DorianBDev** [comment]
I added a commit to try to fix the automatic tests. However, I'm not sure of the problem for the "Installation in private mode" part. Perhaps it's linked to 8fd0849 ?

Changes :
- Change an "rm -rf" to "ynh_secure_remove" for the remove script.
- Add the config file to the backup and restore scripts.
- Fix incorrect "chmod" for the restore and upgrade scripts.
- Fix missing "architecture" variable for the upgrade script.

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
>     * The "arm" branch (that fixes the install on ARM architecture) had an issue with the backend (api) install (not working) due to a file type treated as a binary rather than a zip.
> 

🤔 ...What is downloaded is binaries right? not zip

**Comment by DorianBDev** [comment]
> > ```
> > * The "arm" branch (that fixes the install on ARM architecture) had an issue with the backend (api) install (not working) due to a file type treated as a binary rather than a zip.
> > ```
> 
> 🤔 ...What is downloaded is binaries right? not zip

Strangely, the downloaded file is a zip with binary in it. You can test it by downloading it directly (https://dl.vikunja.io/api/0.18.1/vikunja-v0.18.1-linux-arm64-full) and try to unzip it (or do a `file` on it). Also, you may notice that the "unstable" folder of the download area has the extension `.zip` for all files (https://dl.vikunja.io/api/unstable), so I think it was just a mistake to have files without extensions for the current stable version (0.18.1).

**Comment by ericgaspar** [comment]
Damn! you are right

**Comment by DorianBDev** [comment]
> Meow 🐈 [Test Badge](https://ci-apps-dev.yunohost.org/ci/job/64) [](https://ci-apps-dev.yunohost.org/ci/job/64)

I think it's ready to merge! For the next version, it will be necessary to pay attention to the possible addition of the extension `.zip` in the download files. For now, it should work on all architectures and fix #21.

**Pull request merged**
